// try & catch 


try {
    console.log(a);
}

catch(err) {
    console.log("variable 'a' does not exist");
    console.log(err)
}

// output : variable 'a' does not exist
//          ReferenceError: a is not defined